version: '2'
services:
  db:
    build: ./postgres
    # image: postgres:9.4.1
    ports:
      - "5432:5432"
  web:
    build: ../webserver/
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      - "RAILS_ENV=docker"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/myapp

  frontend:
    build: ./frontend
    # image: httpd:latest
    volumes:
      - ../frontend/dist:/usr/local/apache2/htdocs/
    ports:
      - "4200:80"
    # links:
      # - web
  express:
    build: ../express
    ports:
      - 4201:4201
    volumes:
      - ../express/:/app
