version: '2'
services:
  db:
    build: ./postgres
    image: postgres:9.4.1
    ports:
      - "5432:5432"
  web:
    build: ../
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      - "RAILS_ENV=production"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/myapp

  frontend:
    build: ../frontend
    image: nginx:latest
    volumes:
      - ../frontend/dist/:/usr/share/nginx/html/
    ports:
      - "4200:80"
    links:
      - web
